FROM openjdk:18
LABEL maintainer="javaguides.net"
ADD target/kpopmart_backend-0.0.1-SNAPSHOT.jar kpopmart_backend-0.0.1-SNAPSHOT.jar.original
ENTRYPOINT ["java", "-jar", "kpopmart_backend-0.0.1-SNAPSHOT.jar.original"]